"""Third migration

Revision ID: 16889c485896
Revises: 60aaafae106e
Create Date: 2025-04-01 19:44:50.802307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16889c485896'
down_revision = '60aaafae106e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
