name: Master Build
run-name: master-build

on:
  push:
    branches:
      - main

jobs:
  build:
    secrets: inherit
    permissions:
      packages: write
    uses: ./.github/workflows/wf-build-app.yml
    with:
      push-image: true
      application: ${{ vars.APPLICATION }}