name: PR Build
run-name: pr-build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/wf-build-app.yml
    with:
        push-image: false
        application: ${{ vars.APPLICATION }}